version: '3'

volumes:
  pg_data_fastapi:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_fastapi:/var/lib/postgresql/data

  app:
    image: olegmusatov/blitz_market_app
    env_file: .env
    command: ["/app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
